// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
///
/// IMPORTANT: Replace these placeholder values with your actual Firebase project values.
/// You can get these from the Firebase Console:
/// 1. Go to https://console.firebase.google.com/
/// 2. Select your project
/// 3. Go to Project Settings > General
/// 4. Scroll down to "Your apps" section
/// 5. Add Android/iOS/Web apps if not already added
/// 6. Copy the configuration values
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1DpU4cTHjVOFjSkUWlG5DcXXlxJMqUY4',
    appId: '1:379229858407:web:1b53b75966f7f042cfc2c2',
    messagingSenderId: '379229858407',
    projectId: 'flutter-attendance-625b0',
    authDomain: 'flutter-attendance-625b0.firebaseapp.com',
    storageBucket: 'flutter-attendance-625b0.firebasestorage.app',
    measurementId: 'G-3F7EEFNBJB',
  );

  // TODO: Replace with your actual Firebase Web configuration

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvjlI-gfqvArjQYlqR4a38DsNDKFKxx4c',
    appId: '1:379229858407:android:63d8ab239af88219cfc2c2',
    messagingSenderId: '379229858407',
    projectId: 'flutter-attendance-625b0',
    storageBucket: 'flutter-attendance-625b0.firebasestorage.app',
  );

  // TODO: Replace with your actual Firebase Android configuration

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXRKttPcABHA0Gl9IVhvigVefxU2tDi3g',
    appId: '1:379229858407:ios:b752e32abaee1ff4cfc2c2',
    messagingSenderId: '379229858407',
    projectId: 'flutter-attendance-625b0',
    storageBucket: 'flutter-attendance-625b0.firebasestorage.app',
    iosBundleId: 'com.example.attendance',
  );

  // TODO: Replace with your actual Firebase iOS configuration

  // TODO: Replace with your actual Firebase macOS configuration
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_MACOS_API_KEY',
    appId: '1:YOUR_PROJECT_NUMBER:ios:YOUR_APP_ID',
    messagingSenderId: 'YOUR_PROJECT_NUMBER',
    projectId: 'YOUR_PROJECT_ID',
    storageBucket: 'YOUR_PROJECT_ID.appspot.com',
    iosBundleId: 'com.example.attendance',
  );

  // TODO: Replace with your actual Firebase Windows configuration
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'YOUR_WINDOWS_API_KEY',
    appId: '1:YOUR_PROJECT_NUMBER:web:YOUR_APP_ID',
    messagingSenderId: 'YOUR_PROJECT_NUMBER',
    projectId: 'YOUR_PROJECT_ID',
    authDomain: 'YOUR_PROJECT_ID.firebaseapp.com',
    storageBucket: 'YOUR_PROJECT_ID.appspot.com',
  );
}